### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-normalise bundle size difference from 2.0.1 to d7c664558aa2e3dfd891575ab3f2646936e2ffb4
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-normalise bundle size difference from 2.0.1 to d649b3525a475afcb8f0d0b7953d48a8bebc06d5
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-normalise bundle size difference from 2.0.1 to 36340a60e4ded7a7fc10351f1b224264493667c3
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-normalise bundle size difference from 2.0.1 to 10ab4d814dd9a20d9967b3aaf7c5bf5a2d7da362
No significant bundle size differences found.

**Pull request merged**
